#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AkayouSite
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Akayou.Site")]
	public partial class AkayouSiteDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCadastro(AkayouSite.Db.Cadastro instance);
    partial void UpdateCadastro(AkayouSite.Db.Cadastro instance);
    partial void DeleteCadastro(AkayouSite.Db.Cadastro instance);
    #endregion
		
		public AkayouSiteDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["Akayou_SiteConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public AkayouSiteDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AkayouSiteDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AkayouSiteDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AkayouSiteDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<AkayouSite.Db.Cadastro> Cadastro
		{
			get
			{
				return this.GetTable<AkayouSite.Db.Cadastro>();
			}
		}
	}
}
namespace AkayouSite.Db
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cadastro")]
	public partial class Cadastro : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private string _CadastroGuid;
		
		private bool _Finalizado;
		
		private System.DateTime _DataCadastro;
		
		private System.Nullable<long> _Patrocinador;
		
		private System.Nullable<long> _Upline;
		
		private string _MembershipUserName;
		
		private string _Nome;
		
		private string _Sobrenome;
		
		private string _Cpf;
		
		private string _Rg;
		
		private string _PisPasep;
		
		private System.Nullable<System.DateTime> _DataNascimento;
		
		private string _Cep;
		
		private string _Endereco;
		
		private string _Bairro;
		
		private string _Complemento;
		
		private string _Cidade;
		
		private string _TelCelular;
		
		private string _TelResidencial;
		
		private string _TelComercial;
		
		private string _Email;
		
		private EntitySet<Cadastro> _Cadastro2;
		
		private EntitySet<Cadastro> _Cadastro4;
		
		private EntityRef<Cadastro> _Cadastro1;
		
		private EntityRef<Cadastro> _Cadastro3;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnCadastroGuidChanging(string value);
    partial void OnCadastroGuidChanged();
    partial void OnFinalizadoChanging(bool value);
    partial void OnFinalizadoChanged();
    partial void OnDataCadastroChanging(System.DateTime value);
    partial void OnDataCadastroChanged();
    partial void OnPatrocinadorChanging(System.Nullable<long> value);
    partial void OnPatrocinadorChanged();
    partial void OnUplineChanging(System.Nullable<long> value);
    partial void OnUplineChanged();
    partial void OnMembershipUserNameChanging(string value);
    partial void OnMembershipUserNameChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnSobrenomeChanging(string value);
    partial void OnSobrenomeChanged();
    partial void OnCpfChanging(string value);
    partial void OnCpfChanged();
    partial void OnRgChanging(string value);
    partial void OnRgChanged();
    partial void OnPisPasepChanging(string value);
    partial void OnPisPasepChanged();
    partial void OnDataNascimentoChanging(System.Nullable<System.DateTime> value);
    partial void OnDataNascimentoChanged();
    partial void OnCepChanging(string value);
    partial void OnCepChanged();
    partial void OnEnderecoChanging(string value);
    partial void OnEnderecoChanged();
    partial void OnBairroChanging(string value);
    partial void OnBairroChanged();
    partial void OnComplementoChanging(string value);
    partial void OnComplementoChanged();
    partial void OnCidadeChanging(string value);
    partial void OnCidadeChanged();
    partial void OnTelCelularChanging(string value);
    partial void OnTelCelularChanged();
    partial void OnTelResidencialChanging(string value);
    partial void OnTelResidencialChanged();
    partial void OnTelComercialChanging(string value);
    partial void OnTelComercialChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    #endregion
		
		public Cadastro()
		{
			this._Cadastro2 = new EntitySet<Cadastro>(new Action<Cadastro>(this.attach_Cadastro2), new Action<Cadastro>(this.detach_Cadastro2));
			this._Cadastro4 = new EntitySet<Cadastro>(new Action<Cadastro>(this.attach_Cadastro4), new Action<Cadastro>(this.detach_Cadastro4));
			this._Cadastro1 = default(EntityRef<Cadastro>);
			this._Cadastro3 = default(EntityRef<Cadastro>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CadastroGuid", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string CadastroGuid
		{
			get
			{
				return this._CadastroGuid;
			}
			set
			{
				if ((this._CadastroGuid != value))
				{
					this.OnCadastroGuidChanging(value);
					this.SendPropertyChanging();
					this._CadastroGuid = value;
					this.SendPropertyChanged("CadastroGuid");
					this.OnCadastroGuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Finalizado", DbType="Bit NOT NULL")]
		public bool Finalizado
		{
			get
			{
				return this._Finalizado;
			}
			set
			{
				if ((this._Finalizado != value))
				{
					this.OnFinalizadoChanging(value);
					this.SendPropertyChanging();
					this._Finalizado = value;
					this.SendPropertyChanged("Finalizado");
					this.OnFinalizadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataCadastro", DbType="DateTime NOT NULL")]
		public System.DateTime DataCadastro
		{
			get
			{
				return this._DataCadastro;
			}
			set
			{
				if ((this._DataCadastro != value))
				{
					this.OnDataCadastroChanging(value);
					this.SendPropertyChanging();
					this._DataCadastro = value;
					this.SendPropertyChanged("DataCadastro");
					this.OnDataCadastroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Patrocinador", DbType="BigInt")]
		public System.Nullable<long> Patrocinador
		{
			get
			{
				return this._Patrocinador;
			}
			set
			{
				if ((this._Patrocinador != value))
				{
					if (this._Cadastro3.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPatrocinadorChanging(value);
					this.SendPropertyChanging();
					this._Patrocinador = value;
					this.SendPropertyChanged("Patrocinador");
					this.OnPatrocinadorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Upline", DbType="BigInt")]
		public System.Nullable<long> Upline
		{
			get
			{
				return this._Upline;
			}
			set
			{
				if ((this._Upline != value))
				{
					if (this._Cadastro1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUplineChanging(value);
					this.SendPropertyChanging();
					this._Upline = value;
					this.SendPropertyChanged("Upline");
					this.OnUplineChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MembershipUserName", DbType="NVarChar(256)")]
		public string MembershipUserName
		{
			get
			{
				return this._MembershipUserName;
			}
			set
			{
				if ((this._MembershipUserName != value))
				{
					this.OnMembershipUserNameChanging(value);
					this.SendPropertyChanging();
					this._MembershipUserName = value;
					this.SendPropertyChanged("MembershipUserName");
					this.OnMembershipUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="VarChar(50)")]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sobrenome", DbType="VarChar(50)")]
		public string Sobrenome
		{
			get
			{
				return this._Sobrenome;
			}
			set
			{
				if ((this._Sobrenome != value))
				{
					this.OnSobrenomeChanging(value);
					this.SendPropertyChanging();
					this._Sobrenome = value;
					this.SendPropertyChanged("Sobrenome");
					this.OnSobrenomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cpf", DbType="VarChar(20)")]
		public string Cpf
		{
			get
			{
				return this._Cpf;
			}
			set
			{
				if ((this._Cpf != value))
				{
					this.OnCpfChanging(value);
					this.SendPropertyChanging();
					this._Cpf = value;
					this.SendPropertyChanged("Cpf");
					this.OnCpfChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rg", DbType="VarChar(50)")]
		public string Rg
		{
			get
			{
				return this._Rg;
			}
			set
			{
				if ((this._Rg != value))
				{
					this.OnRgChanging(value);
					this.SendPropertyChanging();
					this._Rg = value;
					this.SendPropertyChanged("Rg");
					this.OnRgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PisPasep", DbType="VarChar(50)")]
		public string PisPasep
		{
			get
			{
				return this._PisPasep;
			}
			set
			{
				if ((this._PisPasep != value))
				{
					this.OnPisPasepChanging(value);
					this.SendPropertyChanging();
					this._PisPasep = value;
					this.SendPropertyChanged("PisPasep");
					this.OnPisPasepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataNascimento", DbType="DateTime")]
		public System.Nullable<System.DateTime> DataNascimento
		{
			get
			{
				return this._DataNascimento;
			}
			set
			{
				if ((this._DataNascimento != value))
				{
					this.OnDataNascimentoChanging(value);
					this.SendPropertyChanging();
					this._DataNascimento = value;
					this.SendPropertyChanged("DataNascimento");
					this.OnDataNascimentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cep", DbType="VarChar(15)")]
		public string Cep
		{
			get
			{
				return this._Cep;
			}
			set
			{
				if ((this._Cep != value))
				{
					this.OnCepChanging(value);
					this.SendPropertyChanging();
					this._Cep = value;
					this.SendPropertyChanged("Cep");
					this.OnCepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Endereco", DbType="VarChar(50)")]
		public string Endereco
		{
			get
			{
				return this._Endereco;
			}
			set
			{
				if ((this._Endereco != value))
				{
					this.OnEnderecoChanging(value);
					this.SendPropertyChanging();
					this._Endereco = value;
					this.SendPropertyChanged("Endereco");
					this.OnEnderecoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bairro", DbType="VarChar(50)")]
		public string Bairro
		{
			get
			{
				return this._Bairro;
			}
			set
			{
				if ((this._Bairro != value))
				{
					this.OnBairroChanging(value);
					this.SendPropertyChanging();
					this._Bairro = value;
					this.SendPropertyChanged("Bairro");
					this.OnBairroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Complemento", DbType="VarChar(50)")]
		public string Complemento
		{
			get
			{
				return this._Complemento;
			}
			set
			{
				if ((this._Complemento != value))
				{
					this.OnComplementoChanging(value);
					this.SendPropertyChanging();
					this._Complemento = value;
					this.SendPropertyChanged("Complemento");
					this.OnComplementoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cidade", DbType="VarChar(50)")]
		public string Cidade
		{
			get
			{
				return this._Cidade;
			}
			set
			{
				if ((this._Cidade != value))
				{
					this.OnCidadeChanging(value);
					this.SendPropertyChanging();
					this._Cidade = value;
					this.SendPropertyChanged("Cidade");
					this.OnCidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelCelular", DbType="VarChar(20)")]
		public string TelCelular
		{
			get
			{
				return this._TelCelular;
			}
			set
			{
				if ((this._TelCelular != value))
				{
					this.OnTelCelularChanging(value);
					this.SendPropertyChanging();
					this._TelCelular = value;
					this.SendPropertyChanged("TelCelular");
					this.OnTelCelularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelResidencial", DbType="VarChar(20)")]
		public string TelResidencial
		{
			get
			{
				return this._TelResidencial;
			}
			set
			{
				if ((this._TelResidencial != value))
				{
					this.OnTelResidencialChanging(value);
					this.SendPropertyChanging();
					this._TelResidencial = value;
					this.SendPropertyChanged("TelResidencial");
					this.OnTelResidencialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelComercial", DbType="VarChar(20)")]
		public string TelComercial
		{
			get
			{
				return this._TelComercial;
			}
			set
			{
				if ((this._TelComercial != value))
				{
					this.OnTelComercialChanging(value);
					this.SendPropertyChanging();
					this._TelComercial = value;
					this.SendPropertyChanged("TelComercial");
					this.OnTelComercialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(30)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cadastro_Cadastro", Storage="_Cadastro2", ThisKey="Id", OtherKey="Upline")]
		public EntitySet<Cadastro> Cadastro2
		{
			get
			{
				return this._Cadastro2;
			}
			set
			{
				this._Cadastro2.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cadastro_Cadastro1", Storage="_Cadastro4", ThisKey="Id", OtherKey="Patrocinador")]
		public EntitySet<Cadastro> Cadastro4
		{
			get
			{
				return this._Cadastro4;
			}
			set
			{
				this._Cadastro4.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cadastro_Cadastro", Storage="_Cadastro1", ThisKey="Upline", OtherKey="Id", IsForeignKey=true)]
		public Cadastro Cadastro1
		{
			get
			{
				return this._Cadastro1.Entity;
			}
			set
			{
				Cadastro previousValue = this._Cadastro1.Entity;
				if (((previousValue != value) 
							|| (this._Cadastro1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Cadastro1.Entity = null;
						previousValue.Cadastro2.Remove(this);
					}
					this._Cadastro1.Entity = value;
					if ((value != null))
					{
						value.Cadastro2.Add(this);
						this._Upline = value.Id;
					}
					else
					{
						this._Upline = default(Nullable<long>);
					}
					this.SendPropertyChanged("Cadastro1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cadastro_Cadastro1", Storage="_Cadastro3", ThisKey="Patrocinador", OtherKey="Id", IsForeignKey=true)]
		public Cadastro Cadastro3
		{
			get
			{
				return this._Cadastro3.Entity;
			}
			set
			{
				Cadastro previousValue = this._Cadastro3.Entity;
				if (((previousValue != value) 
							|| (this._Cadastro3.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Cadastro3.Entity = null;
						previousValue.Cadastro4.Remove(this);
					}
					this._Cadastro3.Entity = value;
					if ((value != null))
					{
						value.Cadastro4.Add(this);
						this._Patrocinador = value.Id;
					}
					else
					{
						this._Patrocinador = default(Nullable<long>);
					}
					this.SendPropertyChanged("Cadastro3");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Cadastro2(Cadastro entity)
		{
			this.SendPropertyChanging();
			entity.Cadastro1 = this;
		}
		
		private void detach_Cadastro2(Cadastro entity)
		{
			this.SendPropertyChanging();
			entity.Cadastro1 = null;
		}
		
		private void attach_Cadastro4(Cadastro entity)
		{
			this.SendPropertyChanging();
			entity.Cadastro3 = this;
		}
		
		private void detach_Cadastro4(Cadastro entity)
		{
			this.SendPropertyChanging();
			entity.Cadastro3 = null;
		}
	}
}
#pragma warning restore 1591
