<?xml version="1.0" encoding="utf-8"?><Database Name="Akayou.Site" EntityNamespace="AkayouSite.Db" Class="AkayouSiteDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=PEDRONOTE\Sqlexpress;Initial Catalog=Akayou.Site;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Akayou_SiteConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.PreCadastro" Member="PreCadastro">
    <Type Name="PreCadastro">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DataCadastro" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CadastradoPor" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="MembershipUserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="NomeCompleto" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Cpf" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Superior" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Association Name="PreCadastro_PreCadastro" Member="PreCadastro2" ThisKey="Id" OtherKey="Superior" Type="PreCadastro" />
      <Association Name="PreCadastro_PreCadastro1" Member="PreCadastro4" ThisKey="Id" OtherKey="CadastradoPor" Type="PreCadastro" />
      <Association Name="PreCadastro_PreCadastro" Member="PreCadastro1" ThisKey="Superior" OtherKey="Id" Type="PreCadastro" IsForeignKey="true" />
      <Association Name="PreCadastro_PreCadastro1" Member="PreCadastro3" ThisKey="CadastradoPor" OtherKey="Id" Type="PreCadastro" IsForeignKey="true" />
    </Type>
  </Table>
</Database>