#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AkayouSite
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Akayou.Site")]
	public partial class AkayouSiteDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertPreCadastro(AkayouSite.Db.PreCadastro instance);
    partial void UpdatePreCadastro(AkayouSite.Db.PreCadastro instance);
    partial void DeletePreCadastro(AkayouSite.Db.PreCadastro instance);
    #endregion
		
		public AkayouSiteDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["Akayou_SiteConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public AkayouSiteDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AkayouSiteDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AkayouSiteDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AkayouSiteDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<AkayouSite.Db.PreCadastro> PreCadastro
		{
			get
			{
				return this.GetTable<AkayouSite.Db.PreCadastro>();
			}
		}
	}
}
namespace AkayouSite.Db
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PreCadastro")]
	public partial class PreCadastro : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private System.DateTime _DataCadastro;
		
		private System.Nullable<long> _CadastradoPor;
		
		private string _MembershipUserName;
		
		private string _NomeCompleto;
		
		private string _Cpf;
		
		private System.Nullable<long> _Superior;
		
		private EntitySet<PreCadastro> _PreCadastro2;
		
		private EntitySet<PreCadastro> _PreCadastro4;
		
		private EntityRef<PreCadastro> _PreCadastro1;
		
		private EntityRef<PreCadastro> _PreCadastro3;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnDataCadastroChanging(System.DateTime value);
    partial void OnDataCadastroChanged();
    partial void OnCadastradoPorChanging(System.Nullable<long> value);
    partial void OnCadastradoPorChanged();
    partial void OnMembershipUserNameChanging(string value);
    partial void OnMembershipUserNameChanged();
    partial void OnNomeCompletoChanging(string value);
    partial void OnNomeCompletoChanged();
    partial void OnCpfChanging(string value);
    partial void OnCpfChanged();
    partial void OnSuperiorChanging(System.Nullable<long> value);
    partial void OnSuperiorChanged();
    #endregion
		
		public PreCadastro()
		{
			this._PreCadastro2 = new EntitySet<PreCadastro>(new Action<PreCadastro>(this.attach_PreCadastro2), new Action<PreCadastro>(this.detach_PreCadastro2));
			this._PreCadastro4 = new EntitySet<PreCadastro>(new Action<PreCadastro>(this.attach_PreCadastro4), new Action<PreCadastro>(this.detach_PreCadastro4));
			this._PreCadastro1 = default(EntityRef<PreCadastro>);
			this._PreCadastro3 = default(EntityRef<PreCadastro>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataCadastro", DbType="DateTime NOT NULL")]
		public System.DateTime DataCadastro
		{
			get
			{
				return this._DataCadastro;
			}
			set
			{
				if ((this._DataCadastro != value))
				{
					this.OnDataCadastroChanging(value);
					this.SendPropertyChanging();
					this._DataCadastro = value;
					this.SendPropertyChanged("DataCadastro");
					this.OnDataCadastroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CadastradoPor", DbType="BigInt")]
		public System.Nullable<long> CadastradoPor
		{
			get
			{
				return this._CadastradoPor;
			}
			set
			{
				if ((this._CadastradoPor != value))
				{
					if (this._PreCadastro3.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCadastradoPorChanging(value);
					this.SendPropertyChanging();
					this._CadastradoPor = value;
					this.SendPropertyChanged("CadastradoPor");
					this.OnCadastradoPorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MembershipUserName", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string MembershipUserName
		{
			get
			{
				return this._MembershipUserName;
			}
			set
			{
				if ((this._MembershipUserName != value))
				{
					this.OnMembershipUserNameChanging(value);
					this.SendPropertyChanging();
					this._MembershipUserName = value;
					this.SendPropertyChanged("MembershipUserName");
					this.OnMembershipUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NomeCompleto", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NomeCompleto
		{
			get
			{
				return this._NomeCompleto;
			}
			set
			{
				if ((this._NomeCompleto != value))
				{
					this.OnNomeCompletoChanging(value);
					this.SendPropertyChanging();
					this._NomeCompleto = value;
					this.SendPropertyChanged("NomeCompleto");
					this.OnNomeCompletoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cpf", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Cpf
		{
			get
			{
				return this._Cpf;
			}
			set
			{
				if ((this._Cpf != value))
				{
					this.OnCpfChanging(value);
					this.SendPropertyChanging();
					this._Cpf = value;
					this.SendPropertyChanged("Cpf");
					this.OnCpfChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Superior", DbType="BigInt")]
		public System.Nullable<long> Superior
		{
			get
			{
				return this._Superior;
			}
			set
			{
				if ((this._Superior != value))
				{
					if (this._PreCadastro1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSuperiorChanging(value);
					this.SendPropertyChanging();
					this._Superior = value;
					this.SendPropertyChanged("Superior");
					this.OnSuperiorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PreCadastro_PreCadastro", Storage="_PreCadastro2", ThisKey="Id", OtherKey="Superior")]
		public EntitySet<PreCadastro> PreCadastro2
		{
			get
			{
				return this._PreCadastro2;
			}
			set
			{
				this._PreCadastro2.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PreCadastro_PreCadastro1", Storage="_PreCadastro4", ThisKey="Id", OtherKey="CadastradoPor")]
		public EntitySet<PreCadastro> PreCadastro4
		{
			get
			{
				return this._PreCadastro4;
			}
			set
			{
				this._PreCadastro4.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PreCadastro_PreCadastro", Storage="_PreCadastro1", ThisKey="Superior", OtherKey="Id", IsForeignKey=true)]
		public PreCadastro PreCadastro1
		{
			get
			{
				return this._PreCadastro1.Entity;
			}
			set
			{
				PreCadastro previousValue = this._PreCadastro1.Entity;
				if (((previousValue != value) 
							|| (this._PreCadastro1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PreCadastro1.Entity = null;
						previousValue.PreCadastro2.Remove(this);
					}
					this._PreCadastro1.Entity = value;
					if ((value != null))
					{
						value.PreCadastro2.Add(this);
						this._Superior = value.Id;
					}
					else
					{
						this._Superior = default(Nullable<long>);
					}
					this.SendPropertyChanged("PreCadastro1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PreCadastro_PreCadastro1", Storage="_PreCadastro3", ThisKey="CadastradoPor", OtherKey="Id", IsForeignKey=true)]
		public PreCadastro PreCadastro3
		{
			get
			{
				return this._PreCadastro3.Entity;
			}
			set
			{
				PreCadastro previousValue = this._PreCadastro3.Entity;
				if (((previousValue != value) 
							|| (this._PreCadastro3.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PreCadastro3.Entity = null;
						previousValue.PreCadastro4.Remove(this);
					}
					this._PreCadastro3.Entity = value;
					if ((value != null))
					{
						value.PreCadastro4.Add(this);
						this._CadastradoPor = value.Id;
					}
					else
					{
						this._CadastradoPor = default(Nullable<long>);
					}
					this.SendPropertyChanged("PreCadastro3");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PreCadastro2(PreCadastro entity)
		{
			this.SendPropertyChanging();
			entity.PreCadastro1 = this;
		}
		
		private void detach_PreCadastro2(PreCadastro entity)
		{
			this.SendPropertyChanging();
			entity.PreCadastro1 = null;
		}
		
		private void attach_PreCadastro4(PreCadastro entity)
		{
			this.SendPropertyChanging();
			entity.PreCadastro3 = this;
		}
		
		private void detach_PreCadastro4(PreCadastro entity)
		{
			this.SendPropertyChanging();
			entity.PreCadastro3 = null;
		}
	}
}
#pragma warning restore 1591
